version: '3'

services:
  pricing:
    build: .
    depends_on:
      - 'database'
      - 'redis'
    ports:
      - '3003:3003'

  database:
    image: postgres:latest

  redis:
    image: redis:latest